name: seu_projeto

description: Um novo projeto Dart com SQLite

publish_to: 'none' # Remova essa linha se você quiser publicar o pacote



version: 1.0.0+1



environment:

  sdk: '>=2.12.0 <3.0.0'



dependencies:

  sqlite3: ^2.1.0 # Adicione esta linha
